export default {
  SEND_METHOD: {
    VERIFICATION_BY_SMS: 'VERIFICATION_BY_SMS',
    VERIFICATION_BY_MESSENGER: 'VERIFICATION_BY_MESSENGER',
  },
  BURGER_PAGES: {
    INDEX: 'INDEX',
    PROFILE: 'PROFILE',
    DISCOUNT: 'DISCOUNT',
    ADDRESS: 'ADDRESS',
    RULES: 'RULES',
    SUPPORT: 'SUPPORT',
    FEEDBACK: 'FEEDBACK',
    FAQ: 'FAQ',
  },
}
