export default {
  // ACTIONS
  LOGIN_LK: 'LOGIN_LK',
  GET_CLIENT_INFO: 'GET_CLIENT_INFO',
  GET_CLIENT_CARD: 'GET_CLIENT_CARD',
  GET_CLIENT_CHEQUES: 'GET_CLIENT_CHEQUES',
  GET_CLIENT_BONUSES: 'GET_CLIENT_BONUSES',
  CLIENT_CREATE_ACTION: 'CLIENT_CREATE_ACTION',
  CLIENT_CREATE_ACTION_2: 'CLIENT_CREATE_ACTION_2',
  CLIENT_CREATE_ISHOP_ACTION: 'CLIENT_CREATE_ISHOP_ACTION',

  // MUTTATIONS
  SET_CLIENT_INFO: 'SET_CLIENT_INFO',
  SET_CLIENT_CARD: 'SET_CLIENT_CARD',
  SET_CLIENT_CHEQUES: 'SET_CLIENT_CHEQUES',
  SET_CLIENT_BONUSES: 'SET_CLIENT_BONUSES',
  SET_CLIENT_ID: 'SET_CLIENT_ID',
}
