export default {
  SET_APP_LOADING: 'SET_APP_LOADING',
  SET_CURRENT_BURGER_PAGE: 'SET_CURRENT_BURGER_PAGE',
  TOGGLE_PANEL_BURGER: 'TOGGLE_PANEL_BURGER',

  // MUTATIONS
  SET_LOADING: 'SET_LOADING',
}
