export default {
  SET_APP_LOADING: 'SET_APP_LOADING',
  SET_CURRENT_BURGER_PAGE: 'SET_CURRENT_BURGER_PAGE',
  TOGGLE_PANEL_BURGER: 'TOGGLE_PANEL_BURGER',
  GET_WIDGET_MAIN_CONFIG_ACTION: 'GET_WIDGET_MAIN_CONFIG_ACTION',
  // MUTATIONS
  SET_LOADING: 'SET_LOADING',
  SET_METADATA: 'SET_METADATA',
  SET_SITECODE: 'SET_SITECODE',
  SET_SOURCEURL: 'SET_SOURCEURL',
  SET_MAIN_WIDGET_CONFIG: 'SET_MAIN_WIDGET_CONFIG',
}
