export default {
  CLEAR_SETTING_INPUT: 'CLEAR_SETTING_INPUT',
  SAVE_SETTINGS_ACTION: 'SAVE_SETTINGS_ACTION',
  SAVE_SETTINGS_PHONE_ACTION: 'SAVE_SETTINGS_PHONE_ACTION',
  SET_SETTINGS_FIO: 'SET_SETTINGS_FIO',
  SET_SETTINGS_PHONE: 'SET_SETTINGS_PHONE',
  SET_SETTINGS_EMAIL: 'SET_SETTINGS_EMAIL',
  SET_SETTINGS_BIRTHDATE: 'SET_SETTINGS_BIRTHDATE',
  SET_SETTINGS_GENDER: 'SET_SETTINGS_GENDER',
  SET_SETTINGS_IS_SAVED: 'SET_SETTINGS_IS_SAVED',
  SET_SETTINGS_PHONE_IS_VERIFY: 'SET_SETTINGS_PHONE_IS_VERIFY',
  SET_SETTINGS_EMAIL_IS_VERIFY: 'SET_SETTINGS_EMAIL_IS_VERIFY',
  SET_SETTINGS_NOTIFY: 'SET_SETTINGS_NOTIFY',
}
