export default {
  SAVE_SETTINGS_ACTION: 'SAVE_SETTINGS_ACTION',
  SET_SETTINGS_FIO: 'SET_SETTINGS_FIO',
  SET_SETTINGS_PHONE: 'SET_SETTINGS_PHONE',
  SET_SETTINGS_EMAIL: 'SET_SETTINGS_EMAIL',
  SET_SETTINGS_BIRTHDATE: 'SET_SETTINGS_BIRTHDATE',
  SET_SETTINGS_GENDER: 'SET_SETTINGS_GENDER',
  SET_SETTINGS_IS_SAVED: 'SET_SETTINGS_IS_SAVED',
}
